dist: trusty
addons:
  chrome: stable

language: php

php:
  - 7.0
  - 7.1
  - 7.2

node_js:
  - "6"

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover